create table if not exists logs ( id INT AUTO_INCREMENT PRIMARY KEY, time DATETIME, source_id INT, level INT NOT NULL, message TEXT );
create table if not exists client_ids ( id INT AUTO_INCREMENT PRIMARY KEY, cpu_uuid UUID );
create table if not exists client_hartbeat ( id INT PRIMARY KEY, time DATETIME );
create table if not exists client_metadata ( id INT PRIMARY KEY, first_seen DATETIME, location VARCHAR(128), description VARCHAR(1024) );
create table if not exists power_monitoring ( id INT AUTO_INCREMENT PRIMARY KEY, time DATETIME, source_id INT, consumption BIGINT );
create table if not exists item_ids ( id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(1024) );
create table if not exists item_stockpiles ( id INT AUTO_INCREMENT PRIMARY KEY, time DATETIME, client_ids INT, item_id INT, amount BIGINT UNSIGNED );

-- Dummy Data generated by GitHub Copilot
-- Insert dummy data into logs
INSERT INTO logs (time, source_id, level, message) VALUES
('2025-06-24 12:00:00', 1, 2, 'System started'),
('2025-06-24 13:00:00', 2, 3, 'Client disconnected'),
('2025-06-24 14:00:00', 1, 1, 'Heartbeat received');

-- Insert dummy data into client_ids
INSERT INTO client_ids (cpu_uuid) VALUES
(UUID()), (UUID()), (UUID());

-- Insert dummy data into client_hartbeat
INSERT INTO client_hartbeat (id, time) VALUES
(1, '2025-06-24 12:05:00'),
(2, '2025-06-24 12:10:00'),
(3, '2025-06-24 12:15:00');

-- Insert dummy data into client_metadata
INSERT INTO client_metadata (id, first_seen, location, description) VALUES
(1, '2025-06-24 11:00:00', 'Berlin', 'Main server in Berlin datacenter'),
(2, '2025-06-24 11:10:00', 'London', 'Backup server in London'),
(3, '2025-06-24 11:20:00', 'New York', 'Edge node NY');

-- Insert dummy data into power_monitoring
INSERT INTO power_monitoring (time, source_id, consumption) VALUES
('2025-06-24 12:00:00', 1, 1200),
('2025-06-24 13:00:00', 2, 1400),
('2025-06-24 14:00:00', 1, 1300);

-- Insert dummy data into item_ids
INSERT INTO item_ids (name) VALUES
('CPU'), ('RAM'), ('SSD'), ('GPU');

-- Insert dummy data into item_stockpiles
INSERT INTO item_stockpiles (time, client_ids, item_id, amount) VALUES
('2025-06-24 12:00:00', 1, 1, 10),
('2025-06-24 12:05:00', 2, 2, 20),
('2025-06-24 12:10:00', 3, 3, 5),
('2025-06-24 12:15:00', 1, 4, 2);